parameters:
  theme.path: ''
  theme.slug: ''

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true


  pattern_category_april_banners:
    class: April\Theme\Patterns\PatternCategoryRegister
    autowire: true
    arguments:
      $slug: 'april-banner'
      $name: 'Theme Banners'
      $description: 'Description is coming soon'


  April\Theme\Patterns\PatternCategoryRegistrar:
    autowire: true
    arguments:
      $patterns:
        - '@pattern_category_april_banners'



