services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true


  pattern_category_april_banners:
    class: Shayerdev\Theme\ThemePatterns\PatternCategoryRegister
    autowire: true
    arguments:
      $slug: 'april-banner'
      $name: 'Theme Banners'
      $description: 'Description is coming soon'


  Shayerdev\Theme\ThemePatterns\PatternCategoryRegistrar:
    autowire: true
    arguments:
      $patterns:
        - '@pattern_category_april_banners'



