parameters:
  theme.path: ''
  theme.slug: ''

imports:
  - { resource: patterns.theme.yaml }
  - { resource: scripts.theme.yaml }
  - { resource: styles.theme.yaml }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
